export const productNames = [
    'Custom',
    '12Cash',
    'AgeOfMonuments',
    'AHappyTurtle',
    'AmazingPlinko',
    'Appflame',
    'Appstation',
    'Appster',
    'CashAlarm',
    'CashArena',
    'CashCow',
    'CashEmAll',
    'CashEmpire',
    'CashGiraffe',
    'CashOnDelivery',
    'CashPaw',
    'CashPong',
    'CashTap',
    'Cashyy',
    'CoinEmpire',
    'CoinPop',
    'FantasyScratch',
    'Fitplay',
    'GameXpert',
    'GetPaid',
    'GoldenFarmery',
    'GolfCash',
    'GreedyDragon',
    'HappySwine',
    'JurassicSlots',
    'JustLotto',
    'JustMines',
    'JustPets',
    'MegaLotto',
    'MegaSlots',
    'MoneyHeist',
    'MoneyRawr',
    'MoneySlots',
    'MoneyTurn',
    'MoneyWell',
    'PlaySmart',
    'PSR',
    'RoyalSlice',
    'Scratch2Win',
    'Scratch4Cash',
    'ScratchCardsPro',
    'ScratchCash',
    'ScratchMagic',
    'Spin4Cash',
    'SwitchRacerCash',
    'SwitchRacerOriginal',
    'TheHappyTurtle',
    'TheLuckyMiner',
    'TimeSlots',
    'WorldOfPlinko',
    'RvM',
    'Scratch4Life',
    'TestEmAll',
];


export const creativeTypes = ['Playable', 'IEC']

export const countryCodes = [
    'ALL',
    'AF',
    'AX',
    'AL',
    'DZ',
    'AS',
    'AD',
    'AO',
    'AI',
    'AQ',
    'AG',
    'AR',
    'AM',
    'AW',
    'AU',
    'AT',
    'AZ',
    'BS',
    'BH',
    'BD',
    'BB',
    'BY',
    'BE',
    'BZ',
    'BJ',
    'BM',
    'BT',
    'BO',
    'BQ',
    'BA',
    'BW',
    'BV',
    'BR',
    'IO',
    'BN',
    'BG',
    'BF',
    'BI',
    'CV',
    'KH',
    'CM',
    'CA',
    'KY',
    'CF',
    'TD',
    'CL',
    'CN',
    'CX',
    'CC',
    'CO',
    'KM',
    'CD',
    'CG',
    'CK',
    'CR',
    'CI',
    'HR',
    'CU',
    'CW',
    'CY',
    'CZ',
    'DK',
    'DJ',
    'DM',
    'DO',
    'EC',
    'EG',
    'SV',
    'GQ',
    'ER',
    'EE',
    'SZ',
    'ET',
    'FK',
    'FO',
    'FJ',
    'FI',
    'FR',
    'GF',
    'PF',
    'TF',
    'GA',
    'GM',
    'GE',
    'DE',
    'GH',
    'GI',
    'GR',
    'GL',
    'GD',
    'GP',
    'GU',
    'GT',
    'GG',
    'GN',
    'GW',
    'GY',
    'HT',
    'HM',
    'VA',
    'HN',
    'HK',
    'HU',
    'IS',
    'IN',
    'ID',
    'IR',
    'IQ',
    'IE',
    'IM',
    'IL',
    'IT',
    'JM',
    'JP',
    'JE',
    'JO',
    'KZ',
    'KE',
    'KI',
    'KP',
    'KR',
    'XK',
    'KW',
    'KG',
    'LA',
    'LV',
    'LB',
    'LS',
    'LR',
    'LY',
    'LI',
    'LT',
    'LU',
    'MO',
    'MG',
    'MW',
    'MY',
    'MV',
    'ML',
    'MT',
    'MH',
    'MQ',
    'MR',
    'MU',
    'YT',
    'MX',
    'FM',
    'MD',
    'MC',
    'MN',
    'ME',
    'MS',
    'MA',
    'MZ',
    'MM',
    'NA',
    'NR',
    'NP',
    'NL',
    'NC',
    'NZ',
    'NI',
    'NE',
    'NG',
    'NU',
    'NF',
    'MK',
    'MP',
    'NO',
    'OM',
    'PK',
    'PW',
    'PS',
    'PA',
    'PG',
    'PY',
    'PE',
    'PH',
    'PN',
    'PL',
    'PT',
    'PR',
    'QA',
    'RE',
    'RO',
    'RU',
    'RW',
    'BL',
    'SH',
    'KN',
    'LC',
    'MF',
    'PM',
    'VC',
    'WS',
    'SM',
    'ST',
    'SA',
    'SN',
    'RS',
    'SC',
    'SL',
    'SG',
    'SX',
    'SK',
    'SI',
    'SB',
    'SO',
    'ZA',
    'GS',
    'SS',
    'ES',
    'LK',
    'SD',
    'SR',
    'SJ',
    'SE',
    'CH',
    'SY',
    'TW',
    'TJ',
    'TZ',
    'TH',
    'TL',
    'TG',
    'TK',
    'TO',
    'TT',
    'TN',
    'TR',
    'TM',
    'TC',
    'TV',
    'UG',
    'UA',
    'AE',
    'GB',
    'US',
    'UM',
    'UY',
    'UZ',
    'VU',
    'VE',
    'VN',
    'VG',
    'VI',
    'WF',
    'EH',
    'YE',
    'ZM',
    'ZW'
];

export interface NetworkData {
    networkID: string
    networkName: string;
    logoPath: string;
    isSelected: boolean;
    isEnable: boolean;
}

export const networkOptions: NetworkData[] = [
    {
        networkID: 'Aarki',
        networkName: 'AARKI',
        logoPath: '/assets/networkLogo/aarkiLogo.svg',
        isSelected: false,
        isEnable: false
    },
    {
        networkID: 'AdColony',
        networkName: 'AdColony',
        logoPath: '/assets/networkLogo/adColonyLogo.svg',
        isSelected: false,
        isEnable: false
    },
    {
        networkID: 'Adjoe',
        networkName: 'Adjoe',
        logoPath: '/assets/networkLogo/adjoeLogo.png',
        isSelected: false,
        isEnable: false
    },
    {
        networkID: 'Applovin',
        networkName: 'Applovin',
        logoPath: '/assets/networkLogo/applovinLogo.svg',
        isSelected: false,
        isEnable: true
    },
    {
        networkID: 'Appreciate',
        networkName: 'Appreciate',
        logoPath: '/assets/networkLogo/appreciateLogo.svg',
        isSelected: false,
        isEnable: false
    },
    {
        networkID: 'Facebook',
        networkName: 'Facebook Gaming',
        logoPath: '/assets/networkLogo/facebookGamingLogo.svg',
        isSelected: false,
        isEnable: false
    },
    {
        networkID: 'GoogleAdManager',
        networkName: 'Google Ad Manager',
        logoPath: '/assets/networkLogo/googleAdManagerLogo.png',
        isSelected: false,
        isEnable: false
    },
    {
        networkID: 'GoogleAds',
        networkName: 'Google Ads',
        logoPath: '/assets/networkLogo/googleAdsLogo.png',
        isSelected: false,
        isEnable: false
    },
    {
        networkID: 'Ironsource',
        networkName: 'Ironsource',
        logoPath: '/assets/networkLogo/ironsourceLogo.svg',
        isSelected: false,
        isEnable: true
    },
    {
        networkID: 'Liftoff',
        networkName: 'Liftoff',
        logoPath: '/assets/networkLogo/liftoffLogo.svg',
        isSelected: false,
        isEnable: false
    },
    {
        networkID: 'Meta',
        networkName: 'Meta',
        logoPath: '/assets/networkLogo/metaLogo.svg',
        isSelected: false,
        isEnable: false
    },
    {
        networkID: 'Mintegral',
        networkName: 'Mintegral',
        logoPath: '/assets/networkLogo/mintegralLogo.svg',
        isSelected: false,
        isEnable: false
    },
    {
        networkID: 'Moloco',
        networkName: 'Moloco',
        logoPath: '/assets/networkLogo/molocoLogo.webp',
        isSelected: false,
        isEnable: false
    },
    {
        networkID: 'Snapchat',
        networkName: 'Snapchat',
        logoPath: '/assets/networkLogo/snapchatLogo.png',
        isSelected: false,
        isEnable: false
    },
    {
        networkID: 'Tencent',
        networkName: 'Tencent',
        logoPath: '/assets/networkLogo/tencentLogo.svg',
        isSelected: false,
        isEnable: false
    },
    {
        networkID: 'Tiktok',
        networkName: 'Tiktok',
        logoPath: '/assets/networkLogo/tiktokLogo.svg',
        isSelected: false,
        isEnable: false
    },
    {
        networkID: 'Unity',
        networkName: 'Unity Ads',
        logoPath: '/assets/networkLogo/unityAdsLogo.svg',
        isSelected: false,
        isEnable: true
    },
    {
        networkID: 'Vungle',
        networkName: 'Vungle',
        logoPath: '/assets/networkLogo/vungleLogo.svg',
        isSelected: false,
        isEnable: true
    },
    {
        networkID: 'YouAppi',
        networkName: 'You APPI',
        logoPath: '/assets/networkLogo/youAppiLogo.svg',
        isSelected: false,
        isEnable: false
    },

];
